### ISSUE TITLE
Pages in Everdev/Command Line Interface

### ISSUE THREAD

**Issue by ArtemFMX333** [everscale-org/docs#127]
Pages how to use instruments through Everdev

- [ ] Solidity page - https://docs.everos.dev/everdev/command-line-interface/solidity
- [ ] C++ - https://docs.everos.dev/everdev/command-line-interface/c
- [ ] Evernode SE - https://docs.everos.dev/everdev/command-line-interface/evernode-platform-startup-edition-se
- [ ] SDK - https://docs.everos.dev/everdev/command-line-interface/sdk
- [ ] TONOS CLI - https://docs.everos.dev/everdev/command-line-interface/tonos-cli
- [ ] TestSuite4 - https://docs.everos.dev/everdev/command-line-interface/testsuite4
- [ ] Signer Tool - https://docs.everos.dev/everdev/command-line-interface/signer-tool
- [ ] Network Tool - https://docs.everos.dev/everdev/command-line-interface/network-tool
- [ ] Contract Management - https://docs.everos.dev/everdev/command-line-interface/contract-management
- [ ] DeBrowser - https://docs.everos.dev/everdev/command-line-interface/debrowser

**Comment by babowsk1** [comment]
[Added](https://github.com/babowsk1/docs/commit/82d9553353ab35c0786ce3efa1fac35ae99b0f7c)
