### ISSUE TITLE
Pages "Developing with Solidity/...."

### ISSUE THREAD

**Issue by ArtemFMX333** [everscale-org/docs#189]
We have to release block of pages in this folder:

- [ ] Getting started
- [ ] Samples
- [ ] Solidity Compiler
- [ ] Comparison with Solidity contracts

**Comment by MaximGerasimenco** [comment]
Do we have samples?

**Comment by ArtemFMX333** [comment]
> Do we have samples?
Sure!)
Reference: https://github.com/tonlabs/samples

**Comment by ArtemFMX333** [comment]
> Do we have samples?

Sure!)
Reference: Sure!)
Reference: https://github.com/tonlabs/samples
