### ISSUE TITLE
https://docs.tonalliance.org/individuals-and-institutionals

### ISSUE THREAD

**Issue by ilyar** [everscale-org/docs#30]
https://docs.tonalliance.org/individuals-and-institutionals

**Comment by babowsk1** [comment]
### Individuals 

- [x] Buy/Store : https://docs.everscale.network/learn/tutorial/users#buy-and-store-tokens
- [x] Popular cases : https://docs.everscale.network/learn/tutorial/users#popular-cases-of-interaction-with-everscale
- [x] Ecosystem : https://docs.everscale.network/learn/everscale-overview/ecosystem

### Institutionals 

https://docs.everscale.network/learn/tutorial/institutionals/tutorial
