### ISSUE TITLE
To create the consensus algorithm section

### ISSUE THREAD

**Issue by MaximGerasimenco** [everscale-org/docs#300]

**Comment by MaximGerasimenco** [comment]
References

https://everscale-community.medium.com/walkthrough-the-catchain-6fb4d25b1d3
https://github.com/tonlabs/ton-labs-node/blob/master/catchain/README.md
https://github.com/tonlabs/ton-labs-node/blob/master/validator-session/README.md

**Comment by ilyar** [comment]
duplicate #285 #251
